#model:
name: 'pemsbay'
num_layers: 2
num_channels: 4
w_out: 100
feat_mixing_hidden_channels: 100
no_mixer_layers: 4
remove_self_loops: True
  
#train:
epochs: 50
learning_rate: 0.0005
batch_size: 64
  
#data:
sequence_length: 2016
target_length: 12
used_link: 325
dataset: 'traffic'
  

  
  
