#model:
name: 'nyctaxi'
num_layers: 2
num_channels: 4
w_out: 100
feat_mixing_hidden_channels: 100
no_mixer_layers: 2
remove_self_loops: True
  
#train:
epochs: 100
learning_rate: 5e-4
batch_size: 5
loss_fn: 1        # 0: MSE loss; 1: MAE loss; 2: Huber loss; 3: Smooth L1 loss
  
#data:
sequence_length: 35
target_length: 1
used_link: 200
dataset: 'traffic'
  
 
